name: ExodiacSkills
author: willowhaus
main: net.exodiac.skills.SkillsPlugin
version: 1.0
description: "Global management to skills features."
depend: [ExodiacCore]
api-version: 1.13
commands:
  essence:
    usage: /<command>